stages:
  - test

variables:
  GITLAB_MAKE: "make -f .gitlab.mk"

# Jobs templates

.release_only_template: &release_only_definition
  only:
    refs:
      - master
      - /^.*-full-ci$/

.docker_test_template: &docker_test_definition
  image: "${CI_REGISTRY}/${CI_PROJECT_PATH}/testing/debian-stretch:latest"
  stage: test
  tags:
    - docker_test

.docker_test_clang8_template: &docker_test_clang8_definition
  image: "${CI_REGISTRY}/${CI_PROJECT_PATH}/testing/debian-buster:latest"
  stage: test
  tags:
    - docker_test

.deploy_template: &deploy_definition
  #<<: *release_only_definition
  stage: test
  tags:
    - deploy_s3
  script:
    - ${GITLAB_MAKE} package

.deploy_test_template: &deploy_test_definition
  <<: *release_only_definition
  stage: test
  tags:
    - deploy_test
  script:
    - ${GITLAB_MAKE} package

.vbox_template: &vbox_definition
  stage: test
  before_script:
    - ${GITLAB_MAKE} vms_start
  after_script:
    - ${GITLAB_MAKE} vms_shutdown

# Packs

#centos_7:
#  <<: *deploy_test_definition
#  variables:
#    OS: 'el'
#    DIST: '7'

ubuntu_14_04:
  <<: *deploy_definition
  variables:
    OS: 'ubuntu'
    DIST: 'trusty'
