name: perf_sysbench

on:
  push:
    tags:
      - '*'
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:
  schedule:
    - cron:  '0 1 * * *'

jobs:
  perf_sysbench:
    if: github.event_name == 'push' ||
        github.event_name == 'repository_dispatch' ||
        github.event_name == 'workflow_dispatch' ||
        github.event_name == 'schedule'

    runs-on: perf-sh3

    strategy:
      fail-fast: false

    steps:
#      TODO: migrate to v2 when Git 2.18 or higher would be available
      - name: checkout tarantool
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: checkout sysbench repo
        uses: actions/checkout@v2.3.4
        with:
          path: sysbench
          repository: tarantool/sysbench
      - name: tarantool build
        run: |
          cmake . -DENABLE_DIST=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo && make -j 4
      - name: configure perf benchmark
        run: |
          ./autogen.sh
          ./configure --with-tarantool --without-mysql
          make -j 4
        working-directory: ./sysbench
      - name: run benchmark
        run: ./run.sh
        working-directory: ./bench-run/benchs/sysbench
      - name: call action to send Telegram message on failure
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_CORE_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_CORE_TO }}
        uses: ./.github/actions/send-telegram-notify
        if: failure()
      - name: artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: perf_sysbench
          retention-days: 21
          path: |
            ./bench-run/benchs/sysbench/*_result.txt
            ./bench-run/benchs/sysbench/*_t_version.txt

# TODO: set up publishing in same job
  publish:
    needs: perf_sysbench
    # TODO: either fix post request availability from perf machines or
    # decide which boxes could be used
    runs-on: ubuntu-latest

    steps:
      - name: checkout tarantool
        uses: actions/checkout@v2.3.4
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
        with:
          name: perf_sysbench
          path: ./bench-run/publish/perf_sysbench
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: install requirements
        run: python3 -m pip install -r ./bench-run/publish/requirements.txt
      - name: publish
        env:
          INFLUXDB_BUCKET_URL: ${{ secrets.INFLUXDB_BUCKET_URL }}
          INFLUXDB_TOKEN: ${{ secrets.INFLUXDB_TOKEN }}
        run: ./publish.py -f ./perf_sysbench
        working-directory: ./bench-run/publish
      - name: call action to send Telegram message on failure
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_CORE_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_CORE_TO }}
        uses: ./.github/actions/send-telegram-notify
        if: failure()
