name: perf_nosqlbench_tree

on:
  push:
    tags:
      - '*'
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:
  schedule:
    - cron:  '0 */3 * * *'

jobs:
  perf_nosqlbench_tree:
    if: github.event_name == 'push' ||
        github.event_name == 'repository_dispatch' ||
        github.event_name == 'workflow_dispatch' ||
        github.event_name == 'schedule'

    runs-on: perf-sh1

    strategy:
      fail-fast: false

    steps:
      - name: set PATH to GIT of the newer version 2.9.0
        run: echo "/usr/local/git/bin" | tee -a $GITHUB_PATH
      - name: cleanup workspace
        run: docker run -w /source -v ${PWD}:/source -i centos:8 /bin/bash -c "chown -R $(id -u):$(id -g) * .[^.]*"
      - uses: actions/checkout@v1
      - name: test
        env:
          BENCH: 'nosqlbench'
          ARG: 'tree'
        uses: ./.github/actions/perf
      - name: call action to send Telegram message on failure
        uses: ./.github/actions/typescript-telegram-notifier
        if: failure()
        with:
          token: ${{ secrets.TELEGRAM_CORE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CORE_TO }}
          parse_mode: MarkdownV2
          disable_web_page_preview: true
      - name: artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: perf_nosqlbench_tree
          retention-days: 21
          path: |
            *_result.txt
            *_t_version.txt
