name: source

on:
  push:
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:

env:
  CI_MAKE: make -f .gitlab.mk

jobs:
  source:
    # We want to run only on tags.
    if: startsWith(github.ref, 'refs/tags/')

    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false

    steps:
      # Permissions correction is needed for self-host runners,
      # where work path is saved between different workflows runs.
      - name: correct permissions in working directory
        shell: bash
        run: |
          sudo chown -R $(id -u):$(id -g) .
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: packaging
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT_URL: ${{ secrets.AWS_S3_ENDPOINT_URL }}
        run: |
          sudo apt-get -y update
          sudo apt-get install -y awscli
          ${CI_MAKE} source_deploy
      - name: call action to send Telegram message on failure
        uses: ./.github/actions/typescript-telegram-notifier
        if: failure()
        with:
          token: ${{ secrets.TELEGRAM_CORE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CORE_TO }}
          parse_mode: MarkdownV2
          disable_web_page_preview: true
